# Generated by Django 4.1 on 2022-09-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_membershipplan_planname'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='UserName',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
