# Generated by Django 4.1 on 2022-09-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_enrollment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='UserName',
        ),
    ]
